# Lable Encoder

In [1]:
import pandas as pd

In [11]:
df = pd.DataFrame({"Name": ["Aman","Nikita","Ajay","OM","Priya","Arpit","Himani","Aman","Nikita","Ajay","OM","Priya","Arpit","Himani"]})

In [12]:
df.head()

     Name
0    Aman
1  Nikita
2    Ajay
3      OM
4   Priya

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

In [15]:
le.fit_transform(df["Name"])

array([1, 4, 0, 5, 6, 2, 3, 1, 4, 0, 5, 6, 2, 3])

In [16]:
df["en_name"] = le.fit_transform(df["Name"])

In [17]:
df

      Name  en_name
0     Aman        1
1   Nikita        4
2     Ajay        0
3       OM        5
4    Priya        6
5    Arpit        2
6   Himani        3
7     Aman        1
8   Nikita        4
9     Ajay        0
10      OM        5
11   Priya        6
12   Arpit        2
13  Himani        3

In [18]:
new_data = df
new_data.to_csv("Label_Encoder.csv",index=False)